### ISSUE TITLE
Encoding Issue in Python3 Runner

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars-runner-cli#558]
I'm trying to fix an issue in [this kata](https://www.codewars.com/kata/hungarian-cardinal-numerals/python) but I'm getting the following error in Python3: 

```python
Unable to decode the command from the command line:
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc5' in position 262: surrogates not allowed
```

**Comment by kazk** [comment]
Are you trying to print something? If so, what happens if you use `.encode("utf-8", "surrogateescape")`?

Can you post the string you're trying to work with?

---

I'll look into Python encoding issues. It's been also reported for Python 2 in #508 and #545.
It might be possible to fix by adjusting environment variables.

```python
import locale
import sys
print(locale.getdefaultlocale())
print(sys.stdout.encoding)
```
from https://wiki.python.org/moin/PrintFails

Python 2.7 outputs:
```
(None, None)
None
```

Python 3.4/3.6 outputs:
```
(None, None)
ANSI_X3.4-1968
```

**Comment by suic86** [comment]
Hi,

I've tried `.encode("utf-8", "surrogateescape")` as I thought that it was because of `print()`. However, taking out the `print`s didn't help. I went through the "encoding exercise" about 3 times. The discussions under my Hungarian language katas contains more information.

**I guess that:**

1. **the issue I have now happens when the code is read before execution** so this is IMO an issue with the runner/docker container so I can't fix it in my code.
2. the issues with printing are caused by different environment variables on different machines. It happened to me, that two different runs on the same version of Python printed different results. I know about `locale.getdefaultlocale()` as I tried them at the time I created those katas. Even these gave different result on different runs.

Thanks,

suic

**Comment by kazk** [comment]
@suic86
Your "Hangarian Cardinal Numerals" works with Python 3.4 by changing the following.

```diff
- print "%s -> %s" % (inp, exp.encode('latin-1'))
+ print("{} -> {}".format(inp, exp))
```

```diff
- print "%s -> %s" % (inp, exp.encode('latin-1'))
+ print("{} -> {}".format(inp, exp))
```

---

I'll try fixing how Python files are handled so
```python
# -*- coding: utf-8 -*-
```
will work as expected for Python 2.

**Comment by kazk** [comment]
I've fixed and deployed the changes.

For Python 2 to work with Non-ASCII characters in source, [the magic comment](https://www.python.org/dev/peps/pep-0263/) is required

```
# -*- coding: utf-8 -*-
```

and `.encode('utf-8')` to print

```
- print "%s -> %s" % (inp, exp.encode('latin-1'))
+ print "%s -> %s" % (inp, exp.encode('utf-8'))
```

Python 3 just works.

**Comment by suic86** [comment]
Hey @kazk,
I've played this a bit. It seems to me that this issue isn't solved.

I got the following error report today (see [here](https://www.codewars.com/kata/hungarian-vowel-harmony-harder/discuss#5ac896c97b620b716200003d)):

```python
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from solution import *
  File "/home/codewarrior/solution.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file /home/codewarrior/solution.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
I was able to repro this with Python 2.7 but only in Trainer. In Kata editor everything works correctly except for the fact, that I'm not able to run my reference solution against Example Test (as Validate Solution runs only the `Test Cases` tab, which I reported quite a while ago but this still doesn't work :/).
However, at the moment, I can't fix this due to `Default Version is not a supported version`. 
I also looked at the Python runner [107](https://github.com/Codewars/codewars-runner-cli/blob/9a4b6a69e4cea22c419729394b5e26e643c024f7/lib/runners/python.js#L107), [108](https://github.com/Codewars/codewars-runner-cli/blob/9a4b6a69e4cea22c419729394b5e26e643c024f7/lib/runners/python.js#L108). IMO a possible solution would be to inject the `# -*- coding: utf-8 -*-` to `solution.py` and the fixture files before running them or specify the encoding in `exec()` (see [here](https://stackoverflow.com/a/30652781)). Also, it would be better to use plain `exec()` instead of `execfile()` for Python 2.

Thanks,

suic

**Comment by kazk** [comment]
> One good solution I can think of is to discontinue Python 2.7 :)

You can do that for your own kata :) I'd rather do that as well from maintainer's point of view, but there're tons of contents that only supports Python 2.

> I got the following error report today

That user's solution lacks the magic comment, so the error is expected.

> Also, it would be better to use plain exec() instead of execfile() for Python 2.

`exec` or `execFile` is not used. This repository is deprecated. See https://github.com/Codewars/codewars-runner-cli/pull/571#issuecomment-375410075 for how it's executed now. Basically just `python file` and some lines are prepended for backwards compatibility. It respects the magic comment and `import __future__` since those needs to be at the beginning of the file.

---

I'll look into the issue that Kata Editor and Trainer is giving inconsistent results.

**Comment by kazk** [comment]
I think the inconsistency between the Editor and the Trainer is that the kata definition used in Trainer was out of date (had started before the change was published).
